spring.application.name: musinsa-order-api
spring.profiles.active: local

---
spring.config.activate.on-profile: local

spring:
  datasource:
    url: jdbc:mysql://localhost:53306/musinsa-order
    username: user
    password: password
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
    show-sql: true
  flyway:
    enabled: true

logging:
  level:
    org.hibernate.type.descriptor.sql.BasicBinder: trace